import { NextResponse } from "next/server";
import dbConnect from "@/lib/db";
import Note from "@/lib/models/Note";
import { protect } from "@/lib/auth";

export async function GET(req) {
  try {
    await dbConnect();
    const user = await protect(req);

    const { searchParams } = new URL(req.url);
    const questionId = searchParams.get("questionId");
    const subject = searchParams.get("subject");

    let query = { userId: user._id };
    if (questionId) query.questionId = questionId;
    if (subject) query.subject = subject;

    const notes = await Note.find(query).sort({ updatedAt: -1 });

    return NextResponse.json({
      success: true,
      count: notes.length,
      data: notes,
    });
  } catch (error) {
    return NextResponse.json(
      { success: false, error: error.message || "Server Error" },
      { status: error.message.includes("Not authorized") ? 401 : 500 }
    );
  }
}

export async function POST(req) {
  try {
    await dbConnect();
    const user = await protect(req);
    const body = await req.json();

    const { questionId, subject, content, _id } = body;

    let note;
    if (_id) {
      // Update existing note
      note = await Note.findOneAndUpdate(
        { _id, userId: user._id },
        { content, subject, questionId },
        { new: true, runValidators: true }
      );
      if (!note) {
        // If ID provided but not found, maybe create new?
        // Or it's a sync of a locally created note that doesn't exist on server yet?
        // If it's a valid ObjectId, we might fail.
        // If it's a temp ID, we should create new.
        // For simplicity, if _id is provided and not found, we treat as create if it looks like a valid ID, or just create new.
        // But usually _id from client for new notes is temp.
        // Let's assume if _id is passed, we try to update. If not found, we create new (removing _id).
        // Actually, standard practice: POST is create, PUT/PATCH is update.
        // But the user asked for POST/GET/DELETE.
        // I'll handle both create and update in POST for simplicity or check if body has _id.
        // If body has _id and it exists, update. Else create.

        // However, Mongoose _id is generated by server usually.
        // If offline created, we might have a temp ID.
        // Let's just create a new one if not found or if no _id.
        note = await Note.create({
          userId: user._id,
          questionId,
          subject,
          content,
        });
      }
    } else {
      note = await Note.create({
        userId: user._id,
        questionId,
        subject,
        content,
      });
    }

    return NextResponse.json({ success: true, data: note });
  } catch (error) {
    return NextResponse.json(
      { success: false, error: error.message || "Server Error" },
      { status: error.message.includes("Not authorized") ? 401 : 500 }
    );
  }
}

export async function DELETE(req) {
  try {
    await dbConnect();
    const user = await protect(req);
    const { searchParams } = new URL(req.url);
    const id = searchParams.get("id");

    if (!id) {
      return NextResponse.json(
        { success: false, error: "Note ID is required" },
        { status: 400 }
      );
    }

    const note = await Note.findOneAndDelete({ _id: id, userId: user._id });

    if (!note) {
      return NextResponse.json(
        { success: false, error: "Note not found" },
        { status: 404 }
      );
    }

    return NextResponse.json({ success: true, data: {} });
  } catch (error) {
    return NextResponse.json(
      { success: false, error: error.message || "Server Error" },
      { status: error.message.includes("Not authorized") ? 401 : 500 }
    );
  }
}
